#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=0:00:15
#PBS -N app-roi-diffusion

time singularity exec -e docker://brainlife/fsl:5.0.9 ./run.sh

if [ ! -f output.csv ]; then
	echo "failed"
	exit 1;
else
	echo "complete"
	exit 0
fi
